In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\full_data.csv")

In [3]:
data

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [5]:
data.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [6]:
data["stroke"].value_counts()

0    4733
1     248
Name: stroke, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
data["gender"]=le.fit_transform(data["gender"])
data["ever_married"]=le.fit_transform(data["ever_married"])
data["work_type"]=le.fit_transform(data["work_type"])
data["Residence_type"]=le.fit_transform(data["Residence_type"])
data["smoking_status"]=le.fit_transform(data["smoking_status"])
data

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  1             228.69  36.6               1       1  
1                  0             105.92  32.5               2       1  
2                  1             171.23  34.4               3       1  
3                  0             174.12  24.0               2       1  
4                  1             186.21  29.0               1       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               1       0  
4977               1             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               1              83.75  29.1               2       0  

[4981 rows x 11 columns]

In [8]:
x1=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

# With using Standard Scalar

In [9]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x = sc.fit_transform(x)

In [10]:
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
x=mn.fit_transform(x1)



In [11]:
x

array([[1.        , 0.81689453, 0.        , ..., 0.80126489, 0.64756447,
        0.33333333],
       [1.        , 0.97558594, 0.        , ..., 0.23451205, 0.53008596,
        0.66666667],
       [0.        , 0.59716797, 0.        , ..., 0.53600776, 0.58452722,
        1.        ],
       ...,
       [0.        , 0.54833984, 1.        , ..., 0.18419352, 0.51002865,
        1.        ],
       [1.        , 0.48730469, 0.        , ..., 0.13304404, 0.45845272,
        1.        ],
       [0.        , 0.97558594, 1.        , ..., 0.13216693, 0.43266476,
        0.66666667]])

In [12]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x_data,y_data=s.fit_resample(x,y)

In [13]:
from collections import Counter
print(Counter(y))
print(Counter(y_data))

Counter({0: 4733, 1: 248})
Counter({1: 4733, 0: 4733})


In [14]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=2,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=5, random_state=2, shuffle=True)


In [15]:
for train_index,test_index in kf.split(x_data):
    print("TRAIN : ",train_index,"TEST : ",test_index)
    x_train,x_test=x_data[train_index],x_data[test_index]
    y_train,y_test=y_data[train_index],y_data[test_index]

    
    
    from sklearn.linear_model import LogisticRegression
    lr=LogisticRegression()
    from sklearn.model_selection import cross_val_score
    scores = cross_val_score(lr, x_train,y_train, cv=kf)
    print(scores)
    print("Mean : ", np.mean(scores)*100)
    
    
    
    from sklearn.model_selection import cross_val_predict
    y_pred=cross_val_predict(lr,x_test,y_test,cv=kf)
    print("Prediction : ",y_pred)
    print("---------------------------------------------------------")
    
    


TRAIN :  [   0    1    2 ... 9462 9463 9464] TEST :  [   3    4   10 ... 9451 9456 9465]
[0.76369637 0.78085809 0.78137384 0.80779392 0.78203435]
Mean :  78.31513138103772
Prediction :  [1 1 0 ... 0 1 1]
---------------------------------------------------------
TRAIN :  [   0    1    3 ... 9462 9463 9465] TEST :  [   2   11   13 ... 9454 9459 9464]
[0.78745875 0.77887789 0.77953795 0.77807133 0.79062087]
Mean :  78.29133587070729
Prediction :  [0 1 1 ... 1 1 1]
---------------------------------------------------------
TRAIN :  [   1    2    3 ... 9462 9464 9465] TEST :  [   0    5    7 ... 9460 9461 9463]
[0.79471947 0.76831683 0.76369637 0.78335535 0.7998679 ]
Mean :  78.19911845874151
Prediction :  [1 1 1 ... 1 1 1]
---------------------------------------------------------
TRAIN :  [   0    1    2 ... 9463 9464 9465] TEST :  [   6    8    9 ... 9449 9457 9458]
[0.77623762 0.78283828 0.78877888 0.77741083 0.77873184]
Mean :  78.07994907813107
Prediction :  [1 1 1 ... 1 1 1]
----------

In [16]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
ac=accuracy_score(y_test,y_pred)*100
cm=confusion_matrix(y_test,y_pred)
cp=classification_report(y_test,y_pred)
print("accuracy score :",ac)
print("confusion matrix :")
print(cm)
print("classification_report :")
print(cp)

accuracy score : 75.91125198098257
confusion matrix :
[[651 269]
 [187 786]]
classification_report :
              precision    recall  f1-score   support

           0       0.78      0.71      0.74       920
           1       0.75      0.81      0.78       973

    accuracy                           0.76      1893
   macro avg       0.76      0.76      0.76      1893
weighted avg       0.76      0.76      0.76      1893

