In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\heart_disease dataset.csv")

In [3]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [5]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [7]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x_data,y_data=s.fit_resample(x,y)

In [8]:
from collections import Counter
print("The Original data :",Counter(y))
print("The Artificial data :",Counter(y_data))


The Original data : Counter({1: 526, 0: 499})
The Artificial data : Counter({0: 526, 1: 526})


In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=2,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=5, random_state=2, shuffle=True)


In [10]:
for train_index,test_index in kf.split(x_data):
    print("TRAIN : ",train_index,"TEST : ",test_index)
    x_train,x_test=x_data[train_index],x_data[test_index]
    y_train,y_test=y_data[train_index],y_data[test_index]

TRAIN :  [   0    1    2    3    4    5    6    8    9   10   11   12   13   14
   16   17   19   21   22   23   24   25   26   27   28   29   30   31
   32   33   34   35   36   38   39   40   41   42   43   44   45   46
   48   49   50   51   52   53   54   55   56   57   58   59   61   62
   63   64   69   72   73   75   76   77   78   79   80   81   82   83
   85   86   87   88   90   92   93   94   95   96   97   98  100  103
  104  105  106  107  108  109  110  111  112  113  114  115  116  117
  118  119  120  121  122  123  124  125  126  127  128  129  130  131
  132  133  134  135  136  138  139  140  142  144  145  147  148  149
  150  151  152  153  154  156  157  159  160  161  162  163  165  166
  167  168  169  170  171  172  173  174  175  176  177  178  179  181
  184  186  187  188  189  190  191  195  196  198  201  202  203  204
  205  206  207  208  209  210  211  214  215  216  217  218  219  220
  221  222  224  225  227  228  229  231  233  234  236  237  238  2

# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr, x_train,y_train, cv=kf)
print(scores)
print(np.mean(scores)*100)

[0.84023669 0.85798817 0.85714286 0.80952381 0.8452381 ]
84.20259227951534


C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [12]:
from sklearn.model_selection import cross_val_predict
y1_pred=cross_val_predict(lr,x_test,y_test,cv=kf)
y1_pred

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac1 = accuracy_score(y_test,y1_pred)*100
cm1 = confusion_matrix(y_test,y1_pred)
print("accuracy score : ",ac1)
print("confusion matrix :")
print(cm1)

accuracy score :  84.28571428571429
confusion matrix :
[[ 75  21]
 [ 12 102]]


# KNN

In [14]:

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)


from sklearn.model_selection import cross_val_score
score_1 = cross_val_score(classifier, x_train,y_train, cv=kf)
print(score_1)
print(np.mean(score_1)*100)

[0.69230769 0.75739645 0.76785714 0.76190476 0.73809524]
74.35122569737955


In [15]:
from sklearn.model_selection import cross_val_predict
y2_pred=cross_val_predict(classifier,x_test,y_test,cv=kf)
y2_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac2 = accuracy_score(y_test,y2_pred)*100
cm2= confusion_matrix(y_test,y2_pred)
print("accuracy score : ",ac2)
print("confusion matrix :")
print(cm2)

accuracy score :  65.23809523809524
confusion matrix :
[[55 41]
 [32 82]]


# SVM

In [ ]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', random_state = 0)
classifier1.fit(x_train, y_train)
from sklearn.model_selection import cross_val_score
score_2 = cross_val_score(classifier1, x_train,y_train, cv=kf)
print(score_2)
print(np.mean(score_2)*100)

In [ ]:
from sklearn.model_selection import cross_val_predict
y3_pred=cross_val_predict(classifier1,x_test,y_test,cv=kf)
y3_pred

In [ ]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac3 = accuracy_score(y_test,y3_pred)*100
cm3 = confusion_matrix(y_test,y3_pred)
print("accuracy score : ",ac3)
print("confusion matrix :")
print(cm3)