In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\Augmented_Iris.csv")

In [3]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0         8.580114       7.411803      2.435236       1.236291      0.395102   
1        79.332857       6.150941      2.058516       4.249965     -0.045997   
2        53.078406       6.444759      3.484995       0.446859      0.708402   
3        61.691342       6.605249      2.324837       0.308108      0.012925   
4        68.423709       5.663883      3.030080       1.279134      2.374453   
...            ...            ...           ...            ...           ...   
999995  119.268226       8.616395      2.504599       0.301577     -0.269477   
999996    3.002019       7.359680      2.822294       2.721681      0.933512   
999997   36.225178       4.638105      2.558795       2.996104      0.747206   
999998   44.642670       8.597138      2.199136       1.997171      0.071688   
999999   44.021513       5.569974      2.565549       0.849239     -0.230247   

                Species  
0           Iris-setosa  
1           Iris-setosa  
2           Iris-setosa  
3           Iris-setosa  
4       Iris-versicolor  
...                 ...  
999995  Iris-versicolor  
999996      Iris-setosa  
999997      Iris-setosa  
999998      Iris-setosa  
999999      Iris-setosa  

[1000000 rows x 6 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype  
---  ------         --------------    -----  
 0   Id             1000000 non-null  float64
 1   SepalLengthCm  1000000 non-null  float64
 2   SepalWidthCm   1000000 non-null  float64
 3   PetalLengthCm  1000000 non-null  float64
 4   PetalWidthCm   1000000 non-null  float64
 5   Species        1000000 non-null  object 
dtypes: float64(5), object(1)
memory usage: 45.8+ MB


In [5]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
data=data.drop(["Id"],axis=1)

In [7]:
data["Species"].value_counts()

Iris-setosa        370520
Iris-virginica     318126
Iris-versicolor    311354
Name: Species, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data["Species"]=l1.fit_transform(data["Species"]) 

In [9]:
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            7.411803      2.435236       1.236291      0.395102        0
1            6.150941      2.058516       4.249965     -0.045997        0
2            6.444759      3.484995       0.446859      0.708402        0
3            6.605249      2.324837       0.308108      0.012925        0
4            5.663883      3.030080       1.279134      2.374453        1
...               ...           ...            ...           ...      ...
999995       8.616395      2.504599       0.301577     -0.269477        1
999996       7.359680      2.822294       2.721681      0.933512        0
999997       4.638105      2.558795       2.996104      0.747206        0
999998       8.597138      2.199136       1.997171      0.071688        0
999999       5.569974      2.565549       0.849239     -0.230247        0

[1000000 rows x 5 columns]

In [10]:
data["Species"].value_counts()

0    370520
2    318126
1    311354
Name: Species, dtype: int64

In [11]:
x=data.iloc[:,0:-1].values
y=data.iloc[:,-1].values

In [12]:
from imblearn.over_sampling import SMOTE
over=SMOTE()
x_data,y_data=SMOTE(k_neighbors=3).fit_resample(x,y)

In [14]:
from collections import Counter
print("Actual data : ",Counter(y))
print("Artificial  data : ",Counter(y_data))

Actual data :  Counter({0: 370520, 2: 318126, 1: 311354})
Artificial  data :  Counter({0: 370520, 1: 370520, 2: 370520})


In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
 
knn = KNeighborsClassifier(n_neighbors = 5, metric="minkowski",p=2)
 
knn.fit(x_train, y_train)


KNeighborsClassifier()

In [17]:
pred = knn.predict(x_test)
pred

array([0, 1, 0, ..., 2, 1, 0])

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred))
 
print(classification_report(y_test, pred))

[[33709 23941 16322]
 [29113 31306 13782]
 [29621 22245 22273]]
              precision    recall  f1-score   support

           0       0.36      0.46      0.41     73972
           1       0.40      0.42      0.41     74201
           2       0.43      0.30      0.35     74139

    accuracy                           0.39    222312
   macro avg       0.40      0.39      0.39    222312
weighted avg       0.40      0.39      0.39    222312

