In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\HousePrice.csv").round(2)

In [3]:
dataset

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK  SQUARE_FT  \
0         Owner                   0     0        2       BHK    1300.24   
1        Dealer                   0     0        2       BHK    1275.00   
2         Owner                   0     0        2       BHK     933.16   
3         Owner                   0     1        2       BHK     929.92   
4        Dealer                   1     0        2       BHK     999.01   
...         ...                 ...   ...      ...       ...        ...   
29446     Owner                   0     0        3       BHK    2500.00   
29447     Owner                   0     0        2       BHK     769.23   
29448    Dealer                   0     0        2       BHK    1022.64   
29449     Owner                   0     0        2       BHK     927.08   
29450    Dealer                   0     1        2       BHK     896.77   

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore      12.97   
1                  1       1          Vishweshwara Nagar,Mysore      12.27   
2                  1       1                   Jigani,Bangalore      12.78   
3                  1       1        Sector-1 Vaishali,Ghaziabad      28.64   
4                  0       1                   New Town,Kolkata      22.59   
...              ...     ...                                ...        ...   
29446              1       1               Shamshabad Road,Agra      27.14   
29447              1       1  E3-108, Lake View Recidency,,Vapi      39.95   
29448              1       1                  Ajmer Road,Jaipur      26.93   
29449              1       1             Sholinganallur,Chennai      12.90   
29450              1       1                   Jagatpura,Jaipur      26.83   

       LATITUDE  TARGET(PRICE_IN_LACS)  
0         77.60                   55.0  
1         76.64                   51.0  
2         77.63                   43.0  
3         77.34                   62.5  
4         88.48                   60.5  
...         ...                    ...  
29446     78.04                   45.0  
29447    -86.15                   16.0  
29448     75.83                   27.1  
29449     80.23                   67.0  
29450     75.84                   27.8  

[29451 rows x 12 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   POSTED_BY              29451 non-null  object 
 1   UNDER_CONSTRUCTION     29451 non-null  int64  
 2   RERA                   29451 non-null  int64  
 3   BHK_NO.                29451 non-null  int64  
 4   BHK_OR_RK              29451 non-null  object 
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64  
 7   RESALE                 29451 non-null  int64  
 8   ADDRESS                29451 non-null  object 
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB


In [5]:
data=dataset.drop("ADDRESS",axis=1)
data

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK  SQUARE_FT  \
0         Owner                   0     0        2       BHK    1300.24   
1        Dealer                   0     0        2       BHK    1275.00   
2         Owner                   0     0        2       BHK     933.16   
3         Owner                   0     1        2       BHK     929.92   
4        Dealer                   1     0        2       BHK     999.01   
...         ...                 ...   ...      ...       ...        ...   
29446     Owner                   0     0        3       BHK    2500.00   
29447     Owner                   0     0        2       BHK     769.23   
29448    Dealer                   0     0        2       BHK    1022.64   
29449     Owner                   0     0        2       BHK     927.08   
29450    Dealer                   0     1        2       BHK     896.77   

       READY_TO_MOVE  RESALE  LONGITUDE  LATITUDE  TARGET(PRICE_IN_LACS)  
0                  1       1      12.97     77.60                   55.0  
1                  1       1      12.27     76.64                   51.0  
2                  1       1      12.78     77.63                   43.0  
3                  1       1      28.64     77.34                   62.5  
4                  0       1      22.59     88.48                   60.5  
...              ...     ...        ...       ...                    ...  
29446              1       1      27.14     78.04                   45.0  
29447              1       1      39.95    -86.15                   16.0  
29448              1       1      26.93     75.83                   27.1  
29449              1       1      12.90     80.23                   67.0  
29450              1       1      26.83     75.84                   27.8  

[29451 rows x 11 columns]

In [6]:
data.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data["POSTED_BY"]=l1.fit_transform(data["POSTED_BY"])

In [8]:
data["POSTED_BY"].value_counts()

1    18291
2    10538
0      622
Name: POSTED_BY, dtype: int64

In [9]:
data["BHK_OR_RK"]=data["BHK_OR_RK"].map({"BHK":1,"RK":0})
data

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO.  BHK_OR_RK  SQUARE_FT  \
0              2                   0     0        2          1    1300.24   
1              1                   0     0        2          1    1275.00   
2              2                   0     0        2          1     933.16   
3              2                   0     1        2          1     929.92   
4              1                   1     0        2          1     999.01   
...          ...                 ...   ...      ...        ...        ...   
29446          2                   0     0        3          1    2500.00   
29447          2                   0     0        2          1     769.23   
29448          1                   0     0        2          1    1022.64   
29449          2                   0     0        2          1     927.08   
29450          1                   0     1        2          1     896.77   

       READY_TO_MOVE  RESALE  LONGITUDE  LATITUDE  TARGET(PRICE_IN_LACS)  
0                  1       1      12.97     77.60                   55.0  
1                  1       1      12.27     76.64                   51.0  
2                  1       1      12.78     77.63                   43.0  
3                  1       1      28.64     77.34                   62.5  
4                  0       1      22.59     88.48                   60.5  
...              ...     ...        ...       ...                    ...  
29446              1       1      27.14     78.04                   45.0  
29447              1       1      39.95    -86.15                   16.0  
29448              1       1      26.93     75.83                   27.1  
29449              1       1      12.90     80.23                   67.0  
29450              1       1      26.83     75.84                   27.8  

[29451 rows x 11 columns]

In [31]:
data["TARGET(PRICE_IN_LACS)"].unique()

array([  55. ,   51. ,   43. , ..., 1170. , 8660. ,   18.3])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   POSTED_BY              29451 non-null  int32  
 1   UNDER_CONSTRUCTION     29451 non-null  int64  
 2   RERA                   29451 non-null  int64  
 3   BHK_NO.                29451 non-null  int64  
 4   BHK_OR_RK              29451 non-null  int64  
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64  
 7   RESALE                 29451 non-null  int64  
 8   LONGITUDE              29451 non-null  float64
 9   LATITUDE               29451 non-null  float64
 10  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int32(1), int64(6)
memory usage: 2.4 MB


In [11]:
data.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [24]:
x=data.iloc[:,5:6].values
print(x)
y=data.iloc[:,-1].values
print(y)

[[1300.24]
 [1275.  ]
 [ 933.16]
 ...
 [1022.64]
 [ 927.08]
 [ 896.77]]
[55.  51.  43.  ... 27.1 67.  27.8]


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
from sklearn.linear_model import LinearRegression
r1=LinearRegression()
r1.fit(x_train,y_train)

LinearRegression()

In [27]:
y_pred=r1.predict(x_test)

In [28]:
y_pred

array([142.37766795, 142.34725036, 142.36051374, ..., 142.37300875,
       142.29698284, 142.46978834])

In [29]:
y_pred1=r1.predict([[934.11]])

In [30]:
y_pred1

array([142.32841632])