# Stratified K Fold Cross Validation

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score

In [2]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\heart_disease dataset.csv")

In [3]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [4]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [6]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=6,random_state=11,shuffle=True)
skf.get_n_splits(x)
print(skf)

StratifiedKFold(n_splits=6, random_state=11, shuffle=True)


In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [8]:
for train_index,test_index in skf.split(x,y):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    scores = cross_val_score(lr, x_train,y_train, cv=skf)
    print(scores)
    print(np.mean(scores)*100)

TRAIN: [   0    1    3    4    5    6    8    9   10   11   12   13   14   15
   16   17   18   19   21   22   23   25   26   27   28   29   30   31
   33   34   35   36   37   38   39   40   42   43   44   45   46   47
   48   49   50   51   52   54   55   57   58   59   61   62   63   65
   66   67   68   69   70   71   72   73   74   75   76   77   78   81
   82   83   84   85   86   87   88   89   90   93   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  125  126  127  128
  129  130  131  132  133  134  135  136  137  138  139  140  142  143
  145  146  147  148  149  150  153  154  155  156  157  158  160  161
  164  165  166  167  168  169  170  171  172  173  174  175  176  177
  178  179  180  181  182  184  186  187  188  189  190  191  192  193
  194  195  197  198  200  201  202  203  204  206  207  210  211  212
  213  214  215  216  217  218  219  220  221  222  224  225  226  227

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

[0.9020979  0.82517483 0.85915493 0.85915493 0.87323944 0.78873239]
85.12590695689286
TRAIN: [   0    2    3    4    6    7    9   10   11   12   13   14   15   16
   17   18   19   20   21   22   24   25   26   27   29   30   31   32
   33   34   37   38   39   41   42   43   44   45   46   47   48   49
   50   51   52   53   54   55   56   57   58   59   60   62   63   64
   65   66   67   68   69   70   72   73   75   76   77   78   79   80
   82   83   84   86   87   88   89   90   91   92   94   95   96   97
   98   99  101  102  103  104  105  106  107  110  111  112  113  116
  117  119  120  121  123  124  125  126  127  128  130  131  132  133
  135  136  137  139  140  141  142  143  144  145  146  147  149  150
  151  152  153  154  155  157  159  160  162  163  164  165  167  168
  169  170  171  172  175  176  177  178  179  180  182  183  184  185
  186  188  189  190  192  193  194  196  197  199  200  201  202  203
  204  205  206  207  208  209  211  214  215  216  217

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

[0.85314685 0.87412587 0.78873239 0.83098592 0.87323944 0.80985915]
83.8348271446863
TRAIN: [   0    1    2    3    5    7    8    9   10   11   12   13   14   15
   17   19   20   22   23   24   25   26   27   28   31   32   33   34
   35   36   37   40   41   42   43   44   45   46   47   50   51   52
   53   56   57   58   59   60   61   62   63   64   65   67   68   69
   70   71   74   76   77   79   80   81   82   83   84   85   86   87
   89   90   91   92   93   94   96   98   99  100  101  102  103  104
  106  108  109  110  111  112  114  115  118  119  121  122  123  124
  125  126  127  128  129  130  132  133  134  136  137  138  141  142
  144  147  148  149  150  151  152  153  154  155  156  157  158  159
  160  161  162  163  164  165  166  168  170  172  173  174  175  176
  177  178  179  180  181  182  183  184  185  186  187  188  189  191
  194  195  196  197  198  199  200  201  203  204  205  206  207  208
  209  210  211  212  213  214  217  218  219  220  221 

[0.81818182 0.84615385 0.83216783 0.84507042 0.82394366 0.85915493]
83.74454184313339


C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [9]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr, x_train,y_train, cv=skf)
print(scores)
print(np.mean(scores)*100)

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

[0.81818182 0.84615385 0.83216783 0.84507042 0.82394366 0.85915493]
83.74454184313339


C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [10]:
from sklearn.model_selection import cross_val_predict
y1_pred=cross_val_predict(lr,x_test,y_test,cv=skf)
print(y1_pred)

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

[1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 0
 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1
 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1
 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0
 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1]


C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 