In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Tech Oral\wine-quality-white-and-red.csv")

In [3]:
data

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493       0.76     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64
 3   citric acid           6497 non-null   float64
 4   residual sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [5]:
data.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
data["quality"].value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data["type"]=l1.fit_transform(data["type"])

In [8]:
data

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        1            7.0             0.270         0.36            20.7   
1        1            6.3             0.300         0.34             1.6   
2        1            8.1             0.280         0.40             6.9   
3        1            7.2             0.230         0.32             8.5   
4        1            7.2             0.230         0.32             8.5   
...    ...            ...               ...          ...             ...   
6492     0            6.2             0.600         0.08             2.0   
6493     0            5.9             0.550         0.10             2.2   
6494     0            6.3             0.510         0.13             2.3   
6495     0            5.9             0.645         0.12             2.0   
6496     0            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493       0.76     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

# Without Imbalancing Techniques

In [9]:
x=data.iloc[:,0:12]
y=data.iloc[:,-1]

In [10]:
y

0       6
1       6
2       6
3       6
4       6
       ..
6492    5
6493    6
6494    6
6495    5
6496    6
Name: quality, Length: 6497, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
 
knn = KNeighborsClassifier(n_neighbors = 1)
 
knn.fit(x_train, y_train)


KNeighborsClassifier(n_neighbors=1)

In [13]:
pred = knn.predict(x_test)
pred

array([6, 6, 5, ..., 6, 7, 6], dtype=int64)

In [14]:
A=knn.predict([[1,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8]])

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [15]:
A

array([6], dtype=int64)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred))
 
print(classification_report(y_test, pred))

[[  0   2   4   0   0   0]
 [  0   8  16  13   7   3]
 [  1   7 272 114  39   5]
 [  1  10 115 344  75  12]
 [  0   4  22  70 115   4]
 [  0   0   2  14   6  15]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.26      0.17      0.21        47
           5       0.63      0.62      0.63       438
           6       0.62      0.62      0.62       557
           7       0.48      0.53      0.50       215
           8       0.38      0.41      0.39        37

    accuracy                           0.58      1300
   macro avg       0.39      0.39      0.39      1300
weighted avg       0.58      0.58      0.58      1300



In [17]:
ab=knn.score(x_test,y_test)*100
ab

57.99999999999999

# Imbalancing Techniques

# 1) oversamling

In [18]:
from imblearn.over_sampling import RandomOverSampler
ro=RandomOverSampler()
x_data,y_data=ro.fit_resample(x,y)

In [19]:
from collections import Counter
print("Actual data : ",Counter(y))
print("Artificial  data : ",Counter(y_data))


Actual data :  Counter({6: 2836, 5: 2138, 7: 1079, 4: 216, 8: 193, 3: 30, 9: 5})
Artificial  data :  Counter({6: 2836, 5: 2836, 7: 2836, 8: 2836, 4: 2836, 3: 2836, 9: 2836})


In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
 
knn = KNeighborsClassifier(n_neighbors = 5, metric="minkowski",p=2)
 
knn.fit(x_train, y_train)


KNeighborsClassifier()

In [22]:
pred1 = knn.predict(x_test)
pred1

array([7, 7, 7, ..., 5, 4, 9], dtype=int64)

In [23]:
B=knn.predict([[1,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8]])
B

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([6], dtype=int64)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred1))
 
print(classification_report(y_test, pred1))

[[613   0   0   0   0   0   0]
 [  0 544   0   0   0   0   0]
 [  4  58 306 101  63  14   1]
 [  3  50 166 205 106  39   0]
 [  2  12  28  63 424  23   0]
 [  0   0   0   4   0 560   0]
 [  0   0   0   0   0   0 582]]
              precision    recall  f1-score   support

           3       0.99      1.00      0.99       613
           4       0.82      1.00      0.90       544
           5       0.61      0.56      0.58       547
           6       0.55      0.36      0.44       569
           7       0.72      0.77      0.74       552
           8       0.88      0.99      0.93       564
           9       1.00      1.00      1.00       582

    accuracy                           0.81      3971
   macro avg       0.79      0.81      0.80      3971
weighted avg       0.80      0.81      0.80      3971



In [25]:
ab1=knn.score(x_test,y_test)*100
ab1

81.4404432132964

# 2) Undersampling

In [26]:
from imblearn.under_sampling import NearMiss
ro=NearMiss()
x1_data,y1_data=ro.fit_resample(x,y)

In [27]:
from collections import Counter
print("Actual data : ",Counter(y))
print("Artificial  data : ",Counter(y1_data))


Actual data :  Counter({6: 2836, 5: 2138, 7: 1079, 4: 216, 8: 193, 3: 30, 9: 5})
Artificial  data :  Counter({3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5})


In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1_data,y1_data,test_size=0.2,random_state=0)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
 
knn = KNeighborsClassifier(n_neighbors = 5, metric="minkowski",p=2)
 
knn.fit(x_train, y_train)


KNeighborsClassifier()

In [30]:
pred2 = knn.predict(x_test)
pred2

array([5, 7, 6, 5, 7, 6, 5], dtype=int64)

In [31]:
C=knn.predict([[1,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8]])
C

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred2))
 
print(classification_report(y_test, pred2))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [2 0 0 0]]
              precision    recall  f1-score   support

           5       0.33      1.00      0.50         1
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         2
           8       0.00      0.00      0.00         2

    accuracy                           0.71         7
   macro avg       0.58      0.75      0.62         7
weighted avg       0.62      0.71      0.64         7



C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
ab2=knn.score(x_test,y_test)*100
ab2

71.42857142857143

# 3) SMOTE

In [34]:
from imblearn.over_sampling import SMOTE
over=SMOTE()
x2_data,y2_data=SMOTE(k_neighbors=3).fit_resample(x,y)

In [35]:
from collections import Counter
print("Actual data : ",Counter(y))
print("Artificial  data : ",Counter(y2_data))


Actual data :  Counter({6: 2836, 5: 2138, 7: 1079, 4: 216, 8: 193, 3: 30, 9: 5})
Artificial  data :  Counter({6: 2836, 5: 2836, 7: 2836, 8: 2836, 4: 2836, 3: 2836, 9: 2836})


In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x2_data,y2_data,test_size=0.2,random_state=0)

In [37]:
from sklearn.neighbors import KNeighborsClassifier
 
knn = KNeighborsClassifier(n_neighbors = 5, metric="minkowski",p=2)
 
knn.fit(x_train, y_train)


KNeighborsClassifier()

In [38]:
pred3 = knn.predict(x_test)
pred3

array([7, 9, 7, ..., 5, 4, 9], dtype=int64)

In [39]:
D=knn.predict([[1,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8]])
D

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([6], dtype=int64)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred3))
 
print(classification_report(y_test, pred3))

[[595   7   7   4   0   0   0]
 [ 10 514  11   3   4   1   1]
 [ 36  64 299  86  42  17   3]
 [ 46  62 132 183  90  41  15]
 [ 13  22  33  29 424  20  11]
 [  0   3   1   4  21 531   4]
 [  0   0   0   0   0   0 582]]
              precision    recall  f1-score   support

           3       0.85      0.97      0.91       613
           4       0.76      0.94      0.85       544
           5       0.62      0.55      0.58       547
           6       0.59      0.32      0.42       569
           7       0.73      0.77      0.75       552
           8       0.87      0.94      0.90       564
           9       0.94      1.00      0.97       582

    accuracy                           0.79      3971
   macro avg       0.77      0.78      0.77      3971
weighted avg       0.77      0.79      0.77      3971



In [41]:
ab3=knn.score(x_test,y_test)*100
ab3

78.77109040543944

# Problem Statements

In [49]:
dataset=x2_data.join(y2_data)

In [50]:
dataset

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0         1       7.000000          0.270000     0.360000       20.700000   
1         1       6.300000          0.300000     0.340000        1.600000   
2         1       8.100000          0.280000     0.400000        6.900000   
3         1       7.200000          0.230000     0.320000        8.500000   
4         1       7.200000          0.230000     0.320000        8.500000   
...     ...            ...               ...          ...             ...   
19847     1       6.786598          0.360000     0.321100        3.217183   
19848     1       7.273990          0.248401     0.414604        2.084007   
19849     1       7.451961          0.240917     0.362751        2.262860   
19850     1       7.131617          0.304412     0.349265        3.180886   
19851     1       6.857177          0.360000     0.332863        3.828865   

       chlorides  free sulfur dioxide  total sulfur dioxide   density  \
0       0.045000            45.000000            170.000000  1.001000   
1       0.049000            14.000000            132.000000  0.994000   
2       0.050000            30.000000             97.000000  0.995100   
3       0.058000            47.000000            186.000000  0.995600   
4       0.058000            47.000000            186.000000  0.995600   
...          ...                  ...                   ...       ...   
19847   0.019134            44.525785            106.147779  0.989743   
19848   0.031420            28.680133            128.079139  0.990445   
19849   0.031122            27.030565            138.541522  0.990747   
19850   0.024022            43.102994            128.264671  0.990147   
19851   0.018428            52.289436            114.146692  0.989779   

             pH  sulphates    alcohol  quality  
0      3.000000   0.450000   8.800000        6  
1      3.300000   0.490000   9.500000        6  
2      3.260000   0.440000  10.100000        6  
3      3.190000   0.400000   9.900000        6  
4      3.190000   0.400000   9.900000        6  
...         ...        ...        ...      ...  
19847  3.329141   0.454502  12.586598        9  
19848  3.317803   0.454798  12.668013        9  
19849  3.277555   0.479389  12.435813        9  
19850  3.280000   0.415588  12.607353        9  
19851  3.298557   0.395686  12.657177        9  

[19852 rows x 13 columns]

# Q.1) Slice a data with red wine whose fixed acidity is (greater than 5) and (less than 9).

In [55]:
red_data = dataset.loc[(dataset["type"]== 1) & (dataset["fixed acidity"]>=5) & (dataset["fixed acidity"]<=9),["type","fixed acidity"]]
red_data

type  fixed acidity
0         1       7.000000
1         1       6.300000
2         1       8.100000
3         1       7.200000
4         1       7.200000
...     ...            ...
19847     1       6.786598
19848     1       7.273990
19849     1       7.451961
19850     1       7.131617
19851     1       6.857177

[14781 rows x 2 columns]

# Q.2) Find out the wine type whose (ph>3 & ph<3.60) and show only type , ph and alcohol.

In [56]:
wine = dataset.loc[(dataset["pH"]>3.0) & (dataset["pH"]<3.60),["type","pH","alcohol"]]

In [57]:
wine

type        pH    alcohol
1         1  3.300000   9.500000
2         1  3.260000  10.100000
3         1  3.190000   9.900000
4         1  3.190000   9.900000
5         1  3.260000  10.100000
...     ...       ...        ...
19847     1  3.329141  12.586598
19848     1  3.317803  12.668013
19849     1  3.277555  12.435813
19850     1  3.280000  12.607353
19851     1  3.298557  12.657177

[18397 rows x 3 columns]

# Q.3) Find out the wine type whose (citric acid < 0.30) and (ph > 3.5).

In [59]:
cp = dataset.loc[(dataset["citric acid"]<0.30) & (dataset["pH"]>3.5), ["type","citric acid","pH"]]
cp

type  citric acid        pH
72        1     0.280000  3.690000
115       1     0.000000  3.630000
250       1     0.280000  3.720000
311       1     0.140000  3.530000
319       1     0.250000  3.540000
...     ...          ...       ...
16234     1     0.150087  3.517620
16246     1     0.281515  3.553074
16367     0     0.278573  3.539990
16760     0     0.083659  3.500283
16867     1     0.262793  3.508106

[820 rows x 3 columns]

# Q.4) Show the quality of wine, whose volatile acidity is between (0.2 to 0.5)

In [61]:
qv = dataset.loc[(dataset["volatile acidity"]>0.2) & (dataset["volatile acidity"]<0.5),["type","quality","volatile acidity"]]
qv

type  quality  volatile acidity
0         1        6          0.270000
1         1        6          0.300000
2         1        6          0.280000
3         1        6          0.230000
4         1        6          0.230000
...     ...      ...               ...
19847     1        9          0.360000
19848     1        9          0.248401
19849     1        9          0.240917
19850     1        9          0.304412
19851     1        9          0.360000

[14013 rows x 3 columns]

In [62]:
qv["volatile acidity"].unique()

array([0.27      , 0.3       , 0.28      , ..., 0.24840066, 0.24091696,
       0.30441197])

# Q.5) Show the data with type ,fixed acidity ,residual sugar ,density whose ph>3.1 and ph<3.9

In [65]:
dataset_1 = dataset.loc[(dataset["pH"]>3.1) & (dataset["pH"]<3.9), ["type","fixed acidity","residual sugar","density","pH"]]
dataset_1

type  fixed acidity  residual sugar   density        pH
1         1       6.300000        1.600000  0.994000  3.300000
2         1       8.100000        6.900000  0.995100  3.260000
3         1       7.200000        8.500000  0.995600  3.190000
4         1       7.200000        8.500000  0.995600  3.190000
5         1       8.100000        6.900000  0.995100  3.260000
...     ...            ...             ...       ...       ...
19847     1       6.786598        3.217183  0.989743  3.329141
19848     1       7.273990        2.084007  0.990445  3.317803
19849     1       7.451961        2.262860  0.990747  3.277555
19850     1       7.131617        3.180886  0.990147  3.280000
19851     1       6.857177        3.828865  0.989779  3.298557

[16209 rows x 5 columns]